#import "/utils.typ": *

= Design, Implementation, and Deployment <chap:design>
This chapter provides a full description of the proposed solution. It details
the system's design process, by discussing the different alternatives (#headref(
  <sec:study-solution>,
)), and describes the proposed architecture (#headref(<sec:sys-architecture>)),
including all components and design decisions.


== Study of the Solution <sec:study-solution>
In order to implement the features described in #headref(<sec:requirements>),
the execution cycle of the simulator had to be modified, as shown in
@alg:creator6-execution-cycle, to incorporate the interrupt, timer, and device
handling subroutines.

#algorithm(
  title: [CREATOR 6's instruction execution cycle],
  label: <alg:creator6-execution-cycle>,
)[
  + Decode _instruction_
  + Increment `PC`
  + Execute _instruction_
  + Handle timers (@alg:creator6-timer-handler)
  + Handle devices (@alg:creator6-device-handler)
  + Handle interrupts (@alg:creator6-interrupt-handler)
  + Fetch _instruction_
]

// why @ end of cycle
The main change with respect to CREATOR 5's execution cycle
(@alg:creator5-execution-cycle) is that the interrupt detection---along with the
timer and devices subroutines---, and the instruction fetch are performed at the
end of the cycle instead of at the beginning of it. The execution order stays
consistent: execute, check for interrupts, and fetch next instruction; but the
with the current approach, the simulator can infer the state after the current
instruction's execution and display it in the UI in the current cycle. This is
relevant for step-by-step execution, as the UI needs to show the next
instruction before the user decides to execute it. In the case of the first
instruction, some extra logic is performed by the assembler in order to fetch
the first instruction.

// why devices -> timers -> int
The order of the interrupt, timer, and device handling is also relevant. An
interrupt can be generated as the result of executing an instruction, but timers
and devices can also generate them, therefore we must check for possible
interrupts _after_ executing those handlers. To allow timers to interact and
influence devices, the timer handler is executed before the device handler.



=== Interrupts <sec:design-interrupt>

// "ponerle puertas al campo"
Simulating interrupts in a "generic" way is a somewhat difficult task. As shown
in @sec:soa-interrupt, each ISA can define its own way of handling interrupts,
but all approaches tend to converge to the same core idea: something unexpected
happens and the processor either ignores it or stops execution, handles it, and
resumes execution. One of the objectives of this simulator is to give the end
users the ability to implement any ISA without needing to implement the whole
simulator, by giving them the optimal tools for the task. The result is a
"generic" interrupt model.

// "generic" interrupt model
The approach is to divide the interrupt model into a set of common actions whose
behaviour is then defined by each specific ISA. The selected interrupt handler
will implement the behaviour of each action. As stated in
@subsec:interrupt-taxonomy, most ISAs differentiate between different interrupt
types, therefore our model must support multiple interrupt types. Some
ISAs---like RISC-V---also support enabling and disabling interrupts globally,
that is, all interrupt types.

#noindent[The set of actions in the model is the following:]
- Generating a specific type of interrupt.
- Evaluating what types of interrupts are currently pending, and returns the
  highest priority one.
- Clearing pending interrupts, both globally and by type.
- Handling a pending interrupt type.
- Enabling and disabling interrupts, either one specific type of interrupt, or
  globally.
- Evaluating if interrupts are enabled, both globally and by type.

// interrupt types
Each ISA defines its own set of interrupt types, but in a generic model it is
possible to differentiate the following#footnote[Note that not all types of
  interrupts need to be defined in all ISAs, the approach is to allow the user
  to select a subset of these types.]:
- _Maskable_: Generic interrupts that can be disabled.
- _NonMaskable_: Generic interrupts that can't be disabled.
- _Timer_: Interrupts generated by a timer.
- _External_: Interrupts generated by an external device.
- _Software_: Interrupts generated by software.
- _EnvironmentCall_: A subset of _software_ interrupts, in which the switch into
  a higher privilege mode of execution---for example, an OS---is required.

// handling subroutine
The handling subroutine, specified in @alg:creator6-interrupt-handler, evaluates
the pending interrupts and executes its handler, if interrupts are globally
enabled and that type of interrupt is enabled. This algorithm only allows for
one type of interrupt to be handled each time, and it's up to the implementation
of the evaluating action to apply the correct priority to each interrupt type
and return the highest priority interrupt. As stated previously, instructions,
timers, and devices can generate interrupts through the use of the specified
action.

#algorithm(
  title: [CREATOR 6's interrupt handling subroutine],
  label: <alg:creator6-interrupt-handler>,
)[
  + *if* _not_ `interruptsGlobalEnabled()` *then*
    + *return*
  - *end if*
  + *if* _not_ `interruptPending()` *then*
    + *return*
  - *end if*
  + `pending_interrupt` $<-$ `getInterrupt()`
  + *if* _not_ $#raw("interruptEnabled(pending_interrupt)")$ *then*
    + *return*
  - *end if*
  + `interruptHandle(pending_interrupt)`
]

/* interrupt handler */

// why? (syscall)
One of the objectives of the interrupt feature in the simulator---as stated in
#highlight[User Requirement XXX]---is for it to be "opt-in", that is, ensuring
that the average user that doesn't need to understand interrupts in order to use
the simulator's basic functionalities. The problem arises with the system calls,
which _must_ be implemented with interrupts, but are part of the basic example
programs of the simulator, as they enable communication with the keyboard and
display. In CREATOR 5, the system call instructions#footnote[`ecall` instruction
  in RISC-V, `syscall` instruction in MIPS-32.] doesn't make use of any type of
interrupts or execution mode changes; instead, it emulates an operating system
by implementing its functionality in the instruction
definition#footnote[Currently, it uses a switch case that reads one or more
  specific registers and calls the desired internal functions.]. The objective
is to allow the user to implement its own interrupt handler, while also
providing a "fallback" system that is transparent for the regular users.

// approaches
There are two possible approaches to solving this: embedding a basic interrupt
handler---written in assembly---with each program, and allowing the user to
replace it; and using multiple interrupt handlers, a default one that bypasses
the architecture-defined interrupt actions, and another that executes the
actions, forcing the user to write their own interrupt handler. The main
difference between the two approaches is that the latter allows writting the
default interrupt handler in JavaScript, which in turns allows interaction with
the system through the CREATOR API (CAPI), offering the user more flexibility
and ease of use. Furthermore, this approach allows switching handlers without
needing to recompile, although this is perhaps only useful for debugging
purposes. For the reasons mentioned, the multiple handler approach was selected.

// y ahora, querido lector, es cuando me he dado cuenta de que elegí mal, pero
// es demasiado tarde para cambiar el código...



=== Timers <sec:design-timer>

// actions
As with interrupts, a generic timer model can be divided into a set of actions:
- Advancing the timer once per tick.
- Handling the different timers, typically evaluating if they reach certain
  threshold and generating an exception if it does.
- Enabling and disabling timers.
- Evaluating if timers are enabled.

// handling subroutine
The timer handling subroutine, specified in @alg:creator6-timer-handler, would
therefore advance and handle the timers once every tick---a tick being a unit of
time composed of one or several clock cycles---if the timers are enabled.

#algorithm(
  title: [CREATOR 6's timer handling subroutine],
  label: <alg:creator6-timer-handler>,
)[
  + *if* _not_ `timerEnabled()` *then*
    + *return*
  - *end if*
  + *if* $#raw("clk_cycles") % #raw("tick_cycles") = 0$ *then*
    + `timerAdvance()`
    + `timerHandle()`
  - *end if*
]


=== Memory-mapped I/O <sec:design-mmio>
// why mmio?
As stated in @sec:soa-devices, there are two main approaches used for I/O
communication in computers: using specific ports for communication, and using
memory. Ports, as they require special instructions, can be emulated in the
instruction definition with CREATOR 6's plugin system #footnote[The plugin
  system defines custom variables and functions in order to better emulate
  specific architectures. These can be accessed---through `CAPI`---in the
  instruction definitions.
], but for ISAs that don't offer those instructions---like RISC-V---,
interaction with the devices the simulator offers can only occur through the use
of MMIO.

// device definition
It is possible to model a "generic" device as a set of registers and a handler
function. Most devices have at least a control register for the CPU to signal an
action to perform, and optionally a status register for the device to broadcast
its status. Instead of a single data register, and to enable more flexibility
for device definition, a data range is provided, that is, a set of contiguous
memory that can be used for communication and to represent several different
registers. The handler is in charge of interacting with the different registers
and interacting with the simulator, having _Direct Memory Access_. A device can
also be enabled or disabled in the architecture definition.

// address decoding
To give the users flexibility over ISA definition, the addresses of the
different devices' registers are configured in the architecture definition. This
also gives the user the ability to map the registers to addresses both inside
and outside main memory#footnote[The size and layout of the main memory is
  already configured in the architecture definition.]. For address decoding, any
access to memory will first check if the address belongs to a device register,
and perform the operation in the device's memory if it does.

// handling subroutine
The device handling subroutine, as shown in @alg:creator6-device-handler,
executes the handler of all enabled devices once per cycle.

#algorithm(
  title: [CREATOR 6's device handling subroutine],
  label: <alg:creator6-device-handler>,
)[
  + *for-each* `device` *in* `devices`
    + *if* _not_ `device.enabled()` *then*
      + *continue*
    - *end if*
    + `device.handler()`
  - *end for-each*
]


== System Architecture <sec:sys-architecture>
// big ol' refactor
#highlight[As per User Requirement XXX,] the system architecture of CREATOR
overhauled. The application was divided into three distinct modules: a _core_
module, containing all the base functionality of the simulator, and two
"consumer" modules, the _Command-Line Interface_ (CLI) and the _Web
Application_. Both consumer modules are separate applications that act as the
interface between the user and the main system's functionality (the core
module)#footnote[Their details are out of the scope of this thesis, but they
  will be briefly described in @sec:implementation.].

// core arch
#noindent[@fig:arch-core shows the core module architecture. Its main components
  are the following:]
- _Architecture Processor_: In charge of parsing the architecture configuration
  file and initializing up the rest of components according to it.
- _Register Manager_: Manages the registers and register operations.
- _Memory Management_: Manages memory access and operations.
- _Execution Engine_: Executes the loaded instuctions and the rest of operations
  in the execution cycle, including interrupts, timers and devices.
- _Assembler_: Assembles and links the source assembly code into a set of
  executable instructions.
- _Sentinel_: Monitors the execution of the program, providing feedback on
  whether parameter passing conventions are followed.
- _CAPI_: An API that defines functions to interact with the rest of the
  components of the system. Includes the plugin system.

#figure(
  image("/diagrams/architecture/core.svg", width: 90%),
  caption: [Core module architecture],
) <fig:arch-core>


=== Interrupt Manager
The Interrupt Manager's interface includes all the actions of the interrupt
model mentioned in @sec:design-interrupt, and is responsible for managing the
different interrupt handlers and keeping track of the interrupt status: if
interrupts are globally enabled, which specific interrupt types are enabled, and
which are pending. It also includes a reset function that clears both the
internal state and any other handler or architecture-defined state, by calling
the clear and enable/disable actions on the handlers---as shown in
@alg:interrupt-manager-reset. As mentioned before, the `handle()` method
implements @alg:creator6-interrupt-handler.

#algorithm(
  title: [Interrupt Manager resetting subroutine],
  label: <alg:interrupt-manager-reset>,
)[
  + *for-each* `type` *in* `interrupt_types` *do* #alg-comment[Enable all
      interrupts]
    + `status.enabled_interrupts[type]` #sym.arrow.l _True_
  - *end for-each*
  + Syncronize interrupts (@alg:interrupt-manager-sync)
  + *for-each* (`enabled`, `type`) *in* `status.pending_interrupts` *do*
    #alg-comment[Clear interrupts]
    + `status.pending_interrupts[type]` #sym.arrow.l _False_
  - *end for-each*
]

// actions and handlers
When an action is performed, the interrupt manager updates its internal status
and executes the corresponding action implemented by its currently selected
handler. This is achieved by making use of an abstract class---as shown in
@fig:arch-interrupts~---which allows maintaining the same interface while having
completely different handler definitions. This approach also allows for easy
addition of new handlers. When switching handlers, the Interrupt Manager makes
use of the internal status and the model actions in order to synchronize the
status---as shown in @alg:interrupt-manager-sync.

#figure(
  image("/diagrams/architecture/interrupts.svg", width: 75%),
  caption: [Interrupt Manager architecture],
) <fig:arch-interrupts>

#algorithm(
  title: [Interrupt Manager syncing subroutine],
  label: <alg:interrupt-manager-sync>,
)[
  + *if* `status.globalEnabled` *then*:
    + `handler.globalEnable()`
  + *else*:
    + `handler.globalDisable()`
  - *end if*
  + *for-each* (`enabled`, `type`) *in* `status.enabled_interrupts` *do*
    + *if* `enabled` *then*:
      + `handler.enable(type)`
    + *else*:
      + `handler.disable(type)`
    - *end if*
  - *end for-each*
]

// implemented handlers
As mentioned before, there are two handlers implemented: the default CREATOR
interrupt handler, and an architecture handler. The former handler treats all
interrupt types except _EnvironmentCall_ as unexpected errors, and generates an
exception that is managed by the UI. For _EnvironmentCall_ interrupts, it
executes the architecture-defined system call handler. The architecture handler
obtains the definition of its actions from the architecture definition, and just
executes them.


=== Timer Manager
The timer manager---shown in @fig:arch-timers~---implements the set of actions
defined in the timer model, which in turn are defined by the architecture, and
the handler executes @alg:creator6-timer-handler.

#figure(
  image("/diagrams/architecture/timers.svg", width: 35%),
  caption: [Timer Manager],
) <fig:arch-timers>


=== Device Manager
The Device Manager---shown in @fig:arch-devices~--- is in charge of executing
@alg:creator6-device-handler, holding the information and handling all the
devices defined in the architecture.

#figure(
  image("/diagrams/architecture/devices.svg", width: 40%),
  caption: [Device Manager architecture],
) <fig:arch-devices>

// devices
Devices all derive from the same abstract class, which implements common methods
such as `isDeviceAddr()`---a method that validates if the given address belongs
to the device---, a reset method---which clears the associated memory---and a
clear method---which resets the control register. Each device then implements
its own handler, and has its own associated memory. This approach makes the
system extensible, making it easier to add new devices.

// implemented devices
The devices implemented are two: a console device that allows reading and
writing to the UI console, and an "OS" driver to interact with the system. The
console device reads the value from the control register and, depending on its
value, performs the read/write operation on the specific data type, using a
register in the data region to pass information, as shown in
@tab:console-device-operations. The OSDriver acts similarly to the console
device, and implements a couple of system operations shown in
@tab:osdriver-operations: _Sbrk_, which allocates memory in the heap, and
_Exit_, which terminates the program.

#figure(
  table(
    columns: 3,
    ..table-header([Control Register value], [Operation], [Data Register
      value]),
    [1], [Print integer], [[in] Integer value to print],
    [2], [Print float], [[in] Float value to print],
    [3], [Print double], [[in] Double value to print],
    [4], [Print string], [[in] Address of the string to print],
    [5], [Read integer], [[out] Value of the integer read],
    [6], [Read float], [[out] Value of the float read],
    [7], [Read double], [[out] Value of the double read],
    [8], [Read string], [[out] Address of the string read],
    [11], [Print char], [[in] Char value to print],
    [12], [Read char], [[out] Value of the char read],
  ),
  caption: [ConsoleDevice operations],
) <tab:console-device-operations>

#figure(
  table(
    columns: 3,
    ..table-header([Control Register value], [Operation], [Data Register
      value]),
    [9],
    [Sbrk],
    [[in] Size to allocate\ [out] Address of allocated memory],
    [10], [Exit], [],
  ),
  caption: [OSDriver operations],
) <tab:osdriver-operations>


=== `CAPI.INTERRUPTS`
As previously stated, CAPI---or CREATOR API---is an interface with the main
system used for in the architecture definition, specially on the instructions
and interrupt/timer actions. In order to allow interactions with the new
features described in this thesis, a new module had to be added, the
`CAPI.INTERRUPTS` module. This module includes the following methods:
- _setUserMode_: Sets the user privilege mode
- _setKernelMode_: Sets the kernel privilege mode.
- _create_: Creates a new interrupt of the specified type.
- _enable_: Enables the specified type of interrupts.
- _globalEnable_: Globally enables interrupts.
- _disable_: Disables the specified type of interrupts.
- _globalDisable_: Globally disables interrupts.
- _isEnabled_: Checks if interrupts of the specified type are enabled.
- _isGlobalEnabled_: Checks if interrupts are globally enabled.
- _clear_: Clears a pending interrupt of the specified type.
- _globalClear_: Clears all pending interrupts.
- _setHandler_: Sets the interrupt handler.



== Implementation <sec:implementation>
// current implementation (cagarse en tó)
CREATOR 5 was written in HTML 5 @html5, CSS 2018 @css2018, and ECMAScript 2019
@ecmascript2019#footnote[More commonly known as "JavaScript".], using the Vue.js
2 web framework @vuejs2. Instead of using ES Modules---introduced in ECMAScript
2015 @ecmascript2015~---the ECMAScript source code was divided into different
logical files and concatenated before deployment. There are many shortcommings
with this approach, specially for the developer experience. Having the code
split in multiple unrelated files requires developers to execute a script each
time they wanted to make a change in the source code, and developer tools such
as linters or language servers are useless, as they don't have access to the
rest of the files. Furthermore, all the variables declared in the top scope of
each file were global variables, allowing accidental _shadowing_#footnote[In
  ECMAScript and other languages, defining a variable with the same name as a
  previously defined variable can re-define the variable, causing undefined or
  unexpected behaviour.] and promoting accessing variables from other logical
files directly instead of through curated interfaces. The Vue components were
implemented inside JavaScript files instead of using Single-File
Components---which require a bundler---, where the HTML definitions were defined
inside JavaScript strings, requiring escaping characters, and generating an
overall diminished developer experience.

// new stuff: TS, ES Modules, Vite, Bun?
The new implementation of the project is built around the Vite build tool
@vite~---the de facto standard for frontend tooling---, and follows modern
conventions for project layout, both on the web application and the CLI. Most of
CREATOR 5's code has been refactored and modified: the inclusion of ES Modules,
the use of classes, Vue Single-File Components, and the addition of new tooling
such as formatters and linters#footnote[Specifically, ESLint @eslint and
  Prettier @prettier.]. The main dependencies and standards were also upgraded:
Vue.js 3, CSS 2025, and ECMAScript 2025, among others. All of this has lead to
an improvement in reliability, mantainability, readability, scalability, and
overall developer experience. Additionally, many of the files were translated
into Typescript @typescript, which improves the robustness of the source code by
adding static typing. It is also important to note the addition of the BigInt
type, which allows us to implement 64-bit architectures#footnote[In ECMAScript,
  the `Number` type stores a 64-bit floating point (double precision) number,
  which only allows integers up to 53 bits.]. The CLI, on the other hand, is
built on top of Deno @deno, a JavaScript runtime, due to its great integration
with WebAssembly @wasm#footnote[CREATOR's default assembler @creatorAssembler is
  written in Rust, and is compiled to WebAssembly in order to be executed in the
  web application. Furthermore, Deno offers a specific target for Rust
  WebAssembly compilation.].

// project layout
@fig:file-structure shows the file structure of the project, in relation with
the components described in @sec:sys-architecture. As CREATOR is primarily a web
application, its structure mainly follows Vite's default template for web
applications. Nevertheless, the source code is clearly separated into the three
main modules: core, web, and CLI.

#import "@preview/treet:1.0.0": tree-list
#figure(
  caption: [Project file structure],
  kind: image, // well, _technically_...
  box(
    width: 90%,
    inset: 10pt,
    fill: luma(93%),
    stroke: black + 1pt,
    radius: 5pt,
    {
      set align(left)
      set text(size: .9em)
      tree-list[
        - `src/`
          - `core/`#tree-comment[Core module]
            - `core.mjs`
            - `assembler/`#tree-comment[Assembler Registry]
              - `assembler.mjs`#tree-comment[Decoder]
              - `creatorAssembler`#tree-comment[CREATOR Assembler]
              - `rasm`#tree-comment[RASM]
              - `sjasmplus`#tree-comment[SJASMPlus]
            // - `sailAssembler`#tree-comment[SAIL Assembler]
            - `capi/`#tree-comment[CAPI]
            - `events.mts`#tree-comment[Events Manager]
            - `executor/`#tree-comment[Execution Engine]
              - `decoder.mjs`#tree-comment[Decoder]
              - `devices.mts`#tree-comment[Device Manager]
              - `executor.mjs`#tree-comment[Executor]
              - `instructionCompiler.mts`#tree-comment[Instruction Compiler]
              - `InterruptManager.mts`#tree-comment[Interrupt Manager]
              - `IO.mjs`#tree-comment[I/O Manager]
              - `stats.mts`#tree-comment[Statistics Tracker]
              - `timers.mts`#tree-comment[Timer Manager]
            - `memory/`#tree-comment[Memory Management]
              - `Memory.mts`#tree-comment[Main Memory]
              - `StackTracker.mts`#tree-comment[Stack Tracker]
            - `register/`#tree-comment[Register Manager]
            - `sentinel/`#tree-comment[Sentinel]
          - `utils/`#tree-comment[Utilities library]
          - `cli/`#tree-comment[CLI module]
          - `web/`#tree-comment[Web application module]
        // - `public/`
        - `architecture/`#tree-comment[Architecture definition files]
        - `examples/`#tree-comment[Example programs]
        - `tests/`#tree-comment[Unit tests]
        - `scripts/`#tree-comment[Build scripts]
        - `index.html`#tree-comment[Web application entrypoint]
        - `package.json`#tree-comment[Project configuration]
        - `vite.config.ts`#tree-comment[Vite configuration]
      ]
    },
  ),
) <fig:file-structure>

// interrupts, timer, devices details
The implementation of interrupts, timers, and MMIO closely follows the designs
in @sec:sys-architecture, with the inclussion of TypeScript Enums and Interfaces
in order to represent the different configurations and types. For the
architecture-defined implementations of timers and interrupts, the `Function`
class---a safer and more effiecient alternative to `eval()`---is used to create
each one of the required actions, and through the use of another wrapper
function, some extra variables are injected into the scope: `CAPI`---a reference
to CAPI---, `status`---a view on the system's status (execution index, clock
cycles, etc.)---, `registers`---a proxy for direct access to the registers---,
and `InterruptType`---an Enum representing the different interrupt types.
Finally, the `Device` class' `memory` attribute is of the same type as the main
memory, as the implementation is generic enough.

// tests
CREATOR 5 included some simple regression tests through the use of the CLI,
consisting of executing specific programs and comparing their outputs. The new
unit tests use the Deno @deno test runner instead, improving reliability and
developer experience. Some components and classes, such as Memory also include
specific unit tests to ensure their correct functionality.


== Deployment <sec:deployment>
// webpage
CREATOR, since its earlier versions, and being a simple web application, could
be deployed on any simple web server, and it has been hosted on GitHub Pages
@github-pages, a service that can be configured to automatically deploy the
latest version of a webpage whose source code is hosted in its own GitHub
repository @CREATORgithub. In order to reduce the size of the ECMAScript code,
the Terser library @terser was used in the building pipeline. With the addition
of Vite, this pipeline is simplified, and produces better results due to the
fact that it also reduces the size of the HTML and CSS, while pruning unused
code.

// CLI, CI
As the CLI is built on top of Deno, it is possible to generate executables for
all the platforms Deno supports: Windows (x86 and ARM architectures), Linux (x86
and ARM architectures), and MacOS (ARM). These executables are built when a new
version is released, and published to the GitHub repository's "Releases" page.
To reduce the executable's size, only the specific core and CLI dependencies are
included.

// specs
The technical specifications recommended for the final user to obtain the best
experience from the application are:
- Operating System: Ubuntu 24.04 LTS (Linux distribution) / Windows 11 / MacOS
  Tahoe.
- Processor: Intel® CoreTM i3 CPU 6300 #sym.at 3.8GHz or higher.
- Random Access Memory (RAM): 2GB or higher.
- Storage: 100MB or free space or higher.
- Network: An Internet connection is required in order for others to access the
  web application, although it can be accessed locally. For deploying the web
  application, an Internet connection is required to download the dependencies.
- Software:
  - Chrome 145 / Safari 26.0 / Firefox 247.0 (Web application).
  - A Node.js @nodejs compatible package manager is required for installing the
    dependencies in order to deploy the web application.
