#import "@preview/cetz:0.4.2"


= State of the art


== Assembly simulators

=== RISC-V Simulators
@SpikeRISCV @VenusRISCV @VenusVSCode


=== Z-80 Simulators

=== Generic simulators
@SpecySim

==== SAIL
@SAIL
@SailRISCV
@Cano2025SAILATOR

==== CREATOR
@Camarmas2021CREATOR


== Interrupts
Authors and vendors use different terms to refer to the same concept, a way of
stopping the current execution of the program due to an exceptional situation.
In this thesis, we'll use _interrupt_.

=== Interrupt Taxonomy
Patterson and Hennery @Patterson2021Exceptions use the term _exception_ to refer
to #quote[[a]n unescheduled event that disrupts program execution; used to
  detect undefined instructions], defining _interrupt_ as #quote[[a]n exception
  that comes from outside the processor]. Bulić @Bulić2024Interrupts, on the
other hand, differentiates between _interrupts_ and _traps_. He defines
interrupts as #quote[signals generated by hardware peripherals or devices to
  signal the processor of an event that requires attention], and distinguishes
between two types: _software_ interrupts, which #quote[function similarly to
  subroutine calls] and #quote[are usually used for requesting operating system
  services], and _external_ interrupts, which are triggered by #quote[[a]n
  external device [...] activating the interrupt request pin on the CPU]. He
further divides the latter into _maskable_, which #quote[can be enabled or
  disabled by setting a bit in the CPU's control register or executing a special
  instruction], and _non-maskable_, which #quote[have a higher priority than
  maskable interrupts]. He also defines _traps_ as #quote[internally generated
  signals that indicate exceptional conditions or errors encountered during the
  execution of program executions] that #quote[require special handling by the
  processor or operating system to resolve and recover from the error].

Undergraduate courses on computer architecture and organization, such as the
ones from the Northern Illinois University @Winans2021Interrupts and Universidad
Carlos III de Madrid @Carballeira2025Interrupts classify _interrupts_ as either
_syncronous_ or _asyncronous_. _Syncronous_ interrupts are generated when an
instruction fails as a result of an error, or by special system call
instructions, and abort the execution of the current instruction; _asyncronous_
interrupts (also called _interrupt requests_) are generated by either a device,
or a timer, and wait for the instruction to finish. This distinction is mainly
relevant in pipelined architectures, where one instruction is performed during
several clock cycles, and an error during the execution of an instruction
compromises the pipeline and requires inmmediate attention.


// RISC-V
The RISC-V ISA @RISCVUnprivileged
// - Exceptions: illegal instructions or errors in the execution of an instruction,
//   generate traps
// - Traps: when changing execution mode
// - Interrupts: generate traps
//   - software, timer, external, counter-overflow


// Z80



=== Interrupt Detection and Handling
// pins
CPUs that support interrupts have an interupt request (_IRQ_) pin and an
interrupt acknowledge (_INTA_) pin, sometimes mapped to a register. When an
interrupt occurs, the IRQ pin is asserted. As the CPU should finish executing
the current instruction before attending the interrupt, a device may have to
wait for several clock cycles before it is attended, so the INTA pin is used to
signal the device that the CPU has started servicing the interrupt request. The
IRQ pin is typically checked before fetching a new instruction.

// execution context
Before handling the interrupt, it is necessary to save the execution context, so
that the program can be resumed when the interrupt handler has completed. The
execution context varies depending on the architecture, and can include, stack
pinter, status register, and any other registers that are visible to the CPU,
but it always includes at least the program counter. This context can be stored
on special registers, on the stack, or in a combination of both, depending on
the architecture. The cause of the interrupt is also typically stored for
architectures that support different types of interrupts.

// Execution/Privilege Mode change


// handler
Different types of interrupts require different procedures to handle them,
therefore there must be a mechanism to execute the correct one for each type.
There are two approaches to this problem: _polled interrupts_ and _vectored
  interrupts_. In the former, the CPU branches to a specific handler address
that typically evaluates the type of interrupt and branches to the handler for
the specific type. The latter, as shown in @fig:vectored-interrupts, implements
an _interrupt vector table_, a table containing _interrupt vectors_, addresses
of interrupt handlers, typically managed by the operating system. The CPU jumps
to each entry depending on the interrupt type, or interrupt exception code. When
the handler has finished, the CPU must restore the previous execution context
and privilege mode. Most architectures include a special instruction to return
from an interrupt with this functionality.

// vectored interrupts diagram
#figure(
  caption: [Vectored interrupts],
  cetz.canvas({
    import cetz.draw: *

    let box-height = .5

    set-style(content: (frame: "rect", stroke: none, fill: none, padding: .1))

    // exception code
    rect((), (rel: (3, box-height)), name: "type")
    content("type", text(size: .8em)[`0x00000004`], anchor: "mid")
    content((rel: (0, -.35), to: "type.south"), [Exception code])

    line("type.north", (rel: (0, box-height)))
    line((), (rel: (2, 0)), mark: (end: ">"))

    // interrupt vector table
    for i in range(4) {
      let id = "iv" + str(i)

      // interrupt vector
      rect(
        (4.5, -i * box-height + box-height * 5 / 2),
        (rel: (4, box-height)),
        name: id,
      )
      content((id), text(size: .8em)[Interrupt Vector #i], anchor: "mid")

      // offset
      content(
        (rel: (-.1, 0), to: "iv" + str(i) + ".west"),
        [`+`#raw(str(4 * i, base: 16))],
        anchor: "mid-east",
      )
    }
    content((rel: (0, .35), to: "iv0.north"), [Interrupt vector table])

    // handler address
    line("iv1.east", (rel: (1, 0)), mark: (end: ">"))
    rect((rel: (0, -box-height / 2)), (rel: (3, box-height)), name: "handler")
    content("handler", text(size: .8em)[`0x00c0ffee`])
    content(
      (rel: (0, .35), to: "handler.north"),
      [Handler address],
    )
  }),
) <fig:vectored-interrupts>



==== RISC-V


==== Z80


=== Interrupt Simulation Implementations


==== Wepsim


==== CREATOR
CREATOR version 3.3 included some initial support for interrupts, specifically
in the MIPS architecture @Camarmas2024CREATOR.


== Timers


== Memory-mapped I/O
