= State of the art


== Assembly simulators

=== Specific Simulators
// RISC-V
@SpikeRISCV @VenusRISCV @VenusVSCode @HaoziwanSim

// Z-80


=== Generic simulators
@SpecySim

==== SAIL
@SAIL
@SailRISCV
@Cano2025SAILATOR

==== CREATOR
@Camarmas2021CREATOR



== Interrupts
Authors and vendors use different terms to refer to the same concept, a way of
stopping the current execution of the program due to an exceptional situation.
In this thesis, we'll use _interrupt_.


=== Interrupt Taxonomy <subsec:interrupt-taxonomy>
// bookz
Patterson and Hennery @Patterson2021Exceptions use the term _exception_ to refer
to #quote[[a]n unescheduled event that disrupts program execution; used to
  detect undefined instructions], defining _interrupt_ as #quote[[a]n exception
  that comes from outside the processor]. Bulić @Bulić2024Interrupts, on the
other hand, differentiates between _interrupts_ and _traps_. He defines
interrupts as #quote[signals generated by hardware peripherals or devices to
  signal the processor of an event that requires attention], and distinguishes
between two types: _software_ interrupts, which #quote[function similarly to
  subroutine calls] and #quote[are usually used for requesting operating system
  services], and _external_ interrupts, which are triggered by #quote[[a]n
  external device [...] activating the interrupt request pin on the CPU]. He
further divides the latter into _maskable_, which #quote[can be enabled or
  disabled by setting a bit in the CPU's control register or executing a special
  instruction], and _non-maskable_, which #quote[have a higher priority than
  maskable interrupts]. He also defines _traps_ as #quote[internally generated
  signals that indicate exceptional conditions or errors encountered during the
  execution of program executions] that #quote[require special handling by the
  processor or operating system to resolve and recover from the error].

// universi-titties
Undergraduate courses on computer architecture and organization, such as the
ones from the Northern Illinois University @Winans2021Interrupts and Universidad
Carlos III de Madrid @Carballeira2025Interrupts classify _interrupts_ as either
_syncronous_ or _asyncronous_. _Syncronous_ interrupts are generated when an
instruction fails as a result of an error, or by special system call
instructions, and abort the execution of the current instruction; _asyncronous_
interrupts (also called _interrupt requests_) are generated by either a device,
or a timer, and wait for the instruction to finish. This distinction is mainly
relevant in pipelined architectures, where one instruction is performed during
several clock cycles, and an error during the execution of an instruction
compromises the pipeline and requires inmmediate attention.

// Z80 & RISC-V
While the Z80 CPU only differentiates between _software maskable interrupts_ and
_nonmaskable interrupts_ @ZilogZ80[p. 17], the RISC-V ISA uses the term
_exception_ as #quote[an unusual condition occurring at run time associated with
  an instruction], while an _interrupt_ is #quote[an external asynchronous event
  that may cause a RISC-V hart to experience an unexpected transfer of control].
It also defines a _trap_ as #quote[the transfer of control to a trap handler
  caused by either an exception or an interrupt], and distinguishes between
_contained_ traps, where #quote[[t]he trap is visible to, and handled by,
  software running inside the execution environment], _requested trap_ where
#quote[[t]he trap is a synchronous exception that is an explicit call to the
  execution environment requesting an action on behalf of software inside the
  execution environment], and #quote[execution may or may not resume on the hart
  after the requested action is taken by the execution environment]; _invisible
  traps_, where #quote[[t]he trap is handled transparently by the execution
  environment and execution resumes normally after the trap is handled]; and a
_fatal trap_, which #quote[represents a fatal failure and causes the execution
  environment to terminate execution] @RISCVUnprivileged[chap. 1.6].


=== Interrupt Detection and Handling
// pins
CPUs that support interrupts have an interupt request (_IRQ_) pin and an
interrupt acknowledge (_INTA_) pin, sometimes mapped to a register. When an
interrupt occurs, the IRQ pin is asserted. As the CPU should finish executing
the current instruction before attending the interrupt, a device may have to
wait for several clock cycles before it is attended, so the INTA pin is used to
signal the device that the CPU has started servicing the interrupt request. The
IRQ pin is typically checked before fetching a new instruction.

// execution context
Before handling the interrupt, it is necessary to save the execution context, so
that the program can be resumed when the interrupt handler has completed. The
execution context varies depending on the architecture, and can include, stack
pinter, status register, and any other registers that are visible to the CPU,
but it always includes at least the program counter. This context can be stored
on special registers, on the stack, or in a combination of both, depending on
the architecture. The cause of the interrupt is also typically stored for
architectures that support different types of interrupts.

// Execution/Privilege Mode change
Modern architectures, such as Intel's x86 @IntelDevManual3A and RISC-V
@RISCVPrivileged, include _privileged modes_ of execution. These modes enable
multiple operating systems, hypervisors, and security models to be implemented
in the same instruction set architecture, by restricting access to certain
instructions and/or control registers to certain modes. The most basic
implementation includes two modes: a _machine_ mode and a _user_ mode, to
prevent user-level applications to run with restricted access to system
resources, although a third _supervisor_ mode, designed for operating system
kernels and with access to some privileged instructions and registers, is
sometimes implemented. In these architectures, when a mode requires executing an
action of higher privilege, such as accessing hardware devices, it generates an
interrupt (also called _trap_ in this specific case) that changes the execution
mode. Interrupts generated by other methods, such as errors during the
execution, also trigger this change.

// handler
Different types of interrupts require different procedures to handle them,
therefore there must be a mechanism to execute the correct one for each type.
There are two approaches to this problem: _polled interrupts_ and _vectored
  interrupts_. In the former, the CPU branches to a specific handler address
that typically evaluates the type of interrupt and branches to the handler for
the specific type. The latter, as shown in @fig:vectored-interrupts, implements
an _interrupt vector table_, a table containing _interrupt vectors_, addresses
of interrupt handlers, typically managed by the operating system. The CPU jumps
to each entry specified in the _interrupt register_. This register is typically
divided into the base address of the interrupt vector table and the interrupt
type, or interrupt exception code, allowing users to specify the address of the
table. Once the handler has finished, usually signaled by some kind of special
"return from interrupt" instruction, the CPU must restore the previous execution
context and privilege mode. Most architectures include a special instruction to
return from an interrupt with this functionality.

// vectored interrupts diagram
#figure(
  caption: [Vectored interrupts],
  include "/diagrams/vectored-interrupts.typ",
) <fig:vectored-interrupts>



==== Interrupts in the RISC-V ISA


==== Interrupts in the Z80 CPU
As mentioned in @subsec:interrupt-taxonomy, the Z80 CPU contains two types on
interrupts, _maskable_, which can be enabled or disabled by the programmer, and
_nonmaskable_, which can't be disabled. To control this, there is an interrupt
enable flip-flop (IFF) that can be either set or reset by the user using
specialized instructions. To account for nonmaskable interrupts, this flip-flop
is split into two, IFF1 and IFF2. When a nonmaskable interrupt ocurs, the status
of IFF1 is stored in IFF2, and IFF1 is reset to prevent maskable interrupts from
interrupting the handler. When the interrupt handler finishes (triggered by the
RTEN instruction), the original value is restored to IFF1 @ZilogZ80[pp. 17-20].

While nonmaskable interrupts are always handled by restarting the CPU at address
`0x0066`, maskable interrupts can be handled by one of the three possible modes,
set by the programmer. In mode 0, the interrupting device places the next
instruction on the data bus, and the CPU executes it. Mode 1 behaves similar to
nonmaskable interrupts, by restarting at address `0x0038`. Finally, mode 3
implements vectored interrupts, using a 16-bit pointer. The upper eight bits of
the pointer are set by the contents of register I, while the lower eight bits
are supplied by the interrupting device.




=== Interrupt Simulation Implementations


==== Wepsim


==== CREATOR
CREATOR version 3.3 included some initial support for interrupts, specifically
in the MIPS architecture @Camarmas2024CREATOR.


== Timers


== Memory-mapped I/O
