#import "/utils.typ": *


= State of the art


== Interrupts
Authors and vendors use different terms to refer to the same concept, a way of
stopping the current execution of the program due to an exceptional situation.
In this thesis, we'll use _interrupt_.


=== Interrupt Taxonomy <subsec:interrupt-taxonomy>
// bookz
Patterson and Hennery @Patterson2021[chap. 4.10] use the term _exception_ to
refer to #quote[[a]n unescheduled event that disrupts program execution; used to
  detect undefined instructions], defining _interrupt_ as #quote[[a]n exception
  that comes from outside the processor]. Bulić @Bulić2024[chap. 2.3.1], on the
other hand, differentiates between _interrupts_ and _traps_. He defines
interrupts as #quote[signals generated by hardware peripherals or devices to
  signal the processor of an event that requires attention], and distinguishes
between two types: _software_ interrupts, which #quote[function similarly to
  subroutine calls] and #quote[are usually used for requesting operating system
  services], and _external_ interrupts, which are triggered by #quote[[a]n
  external device [...] activating the interrupt request pin on the CPU]. He
further divides the latter into _maskable_, which #quote[can be enabled or
  disabled by setting a bit in the CPU's control register or executing a special
  instruction], and _non-maskable_, which #quote[have a higher priority than
  maskable interrupts]. He also defines _traps_ as #quote[internally generated
  signals that indicate exceptional conditions or errors encountered during the
  execution of program executions] that #quote[require special handling by the
  processor or operating system to resolve and recover from the error].

// universi-titties
Undergraduate courses on computer architecture and organization, such as the
ones from the Northern Illinois University @Winans2021Interrupts and Universidad
Carlos III de Madrid @Carballeira2025Interrupts classify _interrupts_ as either
_syncronous_ or _asyncronous_. _Syncronous_ interrupts are generated when an
instruction fails as a result of an error, or by special system call
instructions, and abort the execution of the current instruction; _asyncronous_
interrupts (also called _interrupt requests_) are generated by either a device,
or a timer, and wait for the instruction to finish. This distinction is mainly
relevant in pipelined architectures, where one instruction is performed during
several clock cycles, and an error during the execution of an instruction
compromises the pipeline and requires inmmediate attention.

// Z80 & RISC-V
While the Z80 CPU only differentiates between _software maskable interrupts_ and
_nonmaskable interrupts_ @ZilogZ80[p. 17], the RISC-V ISA uses the term
_exception_ as #quote[an unusual condition occurring at run time associated with
  an instruction], while an _interrupt_ is #quote[an external asynchronous event
  that may cause a RISC-V hart to experience an unexpected transfer of control].
It also defines a _trap_ as #quote[the transfer of control to a trap handler
  caused by either an exception or an interrupt], and distinguishes between
_contained_ traps, where #quote[[t]he trap is visible to, and handled by,
  software running inside the execution environment]\; _requested traps_, where
#quote[[t]he trap is a synchronous exception that is an explicit call to the
  execution environment requesting an action on behalf of software inside the
  execution environment], and #quote[execution may or may not resume on the hart
  after the requested action is taken by the execution environment]\; _invisible
traps_, where #quote[[t]he trap is handled transparently by the execution
  environment and execution resumes normally after the trap is handled]\; and a
_fatal trap_, which #quote[represents a fatal failure and causes the execution
  environment to terminate execution] @RISCVUnprivileged[chap. 1.6].


=== Interrupt Detection and Handling <subsec:interrupt-handling>
// pins
CPUs that support interrupts have an interupt request (_IRQ_) pin and an
interrupt acknowledge (_INTA_) pin, sometimes mapped to a register. When an
interrupt occurs, the IRQ pin is asserted. As the CPU should finish executing
the current instruction before attending the interrupt, a device may have to
wait for several clock cycles before it is attended, so the INTA pin is used to
signal the device that the CPU has started servicing the interrupt request. The
IRQ pin is typically checked before fetching a new instruction.

// execution context
Before handling the interrupt, it is necessary to save the execution context, so
that the program can be resumed when the interrupt handler has completed. The
execution context varies depending on the architecture, and can include, stack
pointer, status register, and any other registers that are visible to the CPU,
but it always includes at least the program counter. This context can be stored
on special registers, on the stack, or in a combination of both, depending on
the architecture. The cause of the interrupt is also stored in architectures
that support different types of interrupts.

// Execution/Privilege Mode change
Modern architectures, such as Intel's x86 @IntelDevManual3A and RISC-V
@RISCVPrivileged, include _privileged modes_ of execution. These modes enable
multiple operating systems, hypervisors, and security models to be implemented
in the same instruction set architecture, by restricting access to certain
instructions and/or control registers to certain modes. The most basic
implementation includes two modes: a _machine_ mode and a _user_ mode, to
prevent user-level applications to run with restricted access to system
resources, although a third _supervisor_ mode, designed for operating system
kernels and with access to some privileged instructions and registers, is
sometimes implemented. In these architectures, when a mode requires executing an
action of higher privilege, such as accessing hardware devices, it generates an
interrupt (also called _trap_ in this specific case) that changes the execution
mode. Interrupts generated by other methods, such as errors during the
execution, also trigger this change.

// handler
Different types of interrupts require different procedures to handle them,
therefore there must be a mechanism to execute the correct one for each type.
There are two approaches to this problem: _polled interrupts_ and _vectored
interrupts_. In the former, the CPU branches to a specific handler address that
typically evaluates the type of interrupt and branches to the handler for the
specific type. The latter, as shown in @fig:vectored-interrupts, implements an
_interrupt vector table_, a table containing _interrupt vectors_, addresses of
interrupt handlers, typically managed by the operating system. The CPU jumps to
each entry specified in the _interrupt register_. This register is typically
divided into the base address of the interrupt vector table and the interrupt
type, or interrupt exception code, allowing users to specify the address of the
table. Once the handler has finished, usually signaled by some kind of special
"return from interrupt" instruction, the CPU must restore the previous execution
context and privilege mode. Most architectures include a special instruction to
return from an interrupt with this functionality.

// vectored interrupts diagram
#figure(
  scale-to-container(include "/diagrams/vectored-interrupts.typ", width: 70%),
  caption: [Vectored interrupts],
  placement: none,
) <fig:vectored-interrupts>



==== Interrupts on the RISC-V-32 ISA <sec:rv32-interrupts>
// privilege levels
As mentioned in @subsec:interrupt-handling, the RISC-V-32 ISA defines different
privilege modes that determine the level of access and control a process has
over the system's resources levels, in particular, access to _Control Status
Registers_ (CSRs)#footnote[The set of instructions to control CSRs is provided
  in the _Zicsr_ extension @RISCVUnprivileged[chap. 7].], the privileged
instruction set, and privileged ISA extensions. The ISA defines three levels:
User/Application (U), Supervisor (S), and Machine (M), allowing implementations
to provide one, two, or three of them #footnote[There are only three supported
  combinations: M-level, M-level and U-level, or all three.]. M-level is the
highest privilege level, while U-level is intended for conventional applications
and S-level for operating systems @RISCVPrivileged[chap. 1.2] @Bulić2024[chap.
  2.5.1].

// CSRs

#let csr-figure(csr) = [
  #figure(
    {
      import "/diagrams/rv32/" + csr + ".typ": diagram
      diagram(width: 75%)
    },
    caption: [#raw(csr) register],
  ) #label("fig:" + csr)
]

#csr-figure("mstatus")
#csr-figure("mie")
#csr-figure("mip")

RISC-V handles exceptions and interrupts, as stated in
@subsec:interrupt-taxonomy, by generating traps. As a trap involves elevating
the privilege level, e.g. requesting an OS system call from a user program, both
M and S privilege levels include a set of CSRs for handling them#footnote[As
  they are virtually the same, we'll only describe the M-level set.]. The
`mstatus` (_Machine Status_) register (@fig:mstatus) keeps track of and controls
the CPU's current operating state. In this register, there are several
interrupt-related fields: field `MIE` (_Machine Interrupt Enable_) controls
whether interrupts are globally enabled or disabled for that privilege mode,
field `MPP` (_Machine Previous Privilege Mode_) holds the previous privilege
mode, and, to allow nesting of interrupts, field `MPIE` stores the previous
value of `MIE` when an interrupt occurs. The `mie` (_Machine Interrupt Enable_)
register (@fig:mie) allows for a finer control of interrupts, allowing the
programmer to set which types of interrupts are enabled: field `MSIE` (_Machine
Software Interrupt Enable_), `MTIE` (_Machine Timer Interrupt Enable_), and
`MEIE` (_Machine External Interrupt Enable_) control software, timer, and
external interrupts, respectively. The `mip` (_Machine Interrupt Pending_)
register (@fig:mip) indicates the interrrupts that are currently pending.
Similarly to register `mie`, it specifies the type of interrupt on specific
fields: `MSIP` (_Machine Software Interrupt Pending_), `MTIP` (_Machine Timer
Interrupt Pending_), and `MEIP` (_Machine External Interrupt Pending_). Each of
these fields may be writable or may be read-only. Register `mcause` (_Machine
Cause_, @fig:mcause) provides information about the event that caused the trap.
This register contains a field `I` specifying if the cause was an interrupt or
an exception, while the rest of the bits are reserved for the exception code.
RISC-V defines some of these exception codes (see @tab:rv32-excodes), while
others are left for the implementation to use. Register `mtvec` (_Machine
Trap-Vector Base-Address_, @fig:mtvec) holds the trap vector configuration.
Depending on the value of the `MODE` field, RISC-V allows for polled interrupts
(_direct mode_, with a value of `0`) or vectored interrupts (_vectored mode_,
with a value of `1`). In direct mode, all traps cause the PC to be set to the
address in the `BASE` field, while on vectored mode, traps set the PC to address
$mono("BASE") + 4 times italic("cause")$, _cause_ being the exception code found
in `mcause`. Finally, register `mepc` (_Machine Exception Program Counter_)
holds the address of the instruction that generated the exception while it is
handled @RISCVUnprivileged[chap. 3.1] @Bulić2024[chap. 2.5.2].

#csr-figure("mcause")
#csr-figure("mtvec")
// #csr-figure("mepc")
#figure(
  table(
    columns: 3,
    ..table-header([I], [Exception Code], [Description]),
    [0], [8], [Environment call from U-mode],
    [1], [3], [Machine software interrupt],
    [1], [7], [Machine timer interrupt],
    [1], [11], [Machine external interrupt],
  ),
  caption: [List of relevant `mcause` register values],
) <tab:rv32-excodes>


// handling
When a trap is taken to M-mode, the corresponding flag in `mip` is set, and the
`MIE` field in `mstatus` and the corresponding flag in `mie` are checked to
determine if that interrupt is enabled. If it's enabled, the `MIE` field is
copied into the `MPIE` field of `mstatus` and `MIE` is cleared, disabling
further interrupts. Then, the previous privilege mode is stored in the `MPP`
field of `mstatus`, the cause of the exception is encoded into `mcause`, the
current PC is stored into the `mepc` register, and the PC is set to the address
specified by `mtvec`. When the interrupt handler finishes, it calls `mret`,
which resets the privilege mode (reading the `MPP` field in `mstatus`),
re-enables interrupts (by copying back field `MPIE` to `MIE` in `mstatus`), and
sets the PC to the value of `mepc`. With regard to the `mip` register, the ISA
states that if the field is writable, a pending interrupt can be cleared by
clearing it, but if the field is read-only, the implementation must provide some
other mechanism for clearing the pending interrupt @RISCVUnprivileged[chap. 3.3]
@Bulić2024[chap. 2.5.4].


==== Interrupts on the Z80 CPU
// detection
As discussed in @subsec:interrupt-taxonomy, the Z80 CPU contains two types on
interrupts, _maskable_, which can be enabled or disabled by the programmer, and
_nonmaskable_, which can't be disabled. To control this, there is an interrupt
enable flip-flop (`IFF`) that can be either set or reset by the user using
specialized instructions. To account for nonmaskable interrupts, this flip-flop
is split into two, `IFF1` and `IFF2`. When a nonmaskable interrupt ocurs, the
status of `IFF1` is stored in `IFF2`, and `IFF1` is reset to prevent maskable
interrupts from interrupting the handler. When the interrupt handler finishes
(triggered by the `RTEN` instruction), the original value is restored to IFF1
@ZilogZ80[pp. 17--18].

// handling
While nonmaskable interrupts are always handled by restarting the CPU at address
`0x0066`, maskable interrupts can be handled by one of the three possible modes,
set by the programmer. In mode 0, the interrupting device places the next
instruction on the data bus, and the CPU executes it. Mode 1 behaves similar to
nonmaskable interrupts, by restarting at address `0x0038`. Finally, mode 3
implements vectored interrupts, using a 16-bit pointer. The upper eight bits of
the pointer are set by the contents of register `I`, while the lower eight bits
are supplied by the interrupting device @ZilogZ80[pp. 19--20].



=== Interrupt Simulation
// assembly simulators
An _assembly simulator_ is a piece of software that emulates a specific
Instruction Set Architecture (ISA) CPU and allows the user to program it through
its assembly language. Its purpose is usually educational, in order to aid the
user in learning the lenguage; or as a development tool, a quick way to iterate
through different hardware designs without the cost of physically manufacturing
components.

// specific simulators
Most of the assembly simulators that exist are tailored to one specific ISA. In
ISAs that have well-defined simple interrupt mechanisms, simulators such as
YAZE-AG @YAZESim just implement interrupts as described. On the other hand, ISAs
that give the manufacturer flexibility to implement its features, like the
RISC-V ISA, varie more. While SAILATOR @Cano2025SAILATOR, based on SAIL's RISC-V
ISA definition#footnote[SAIL @SAIL is a definition language for ISAs, that also
  can generate a simulator from the definition.] @SailRISCV implements the
registers described in @subsec:interrupt-handling and bundles its own kernel to
handle traps, Spike @SpikeRISCV, one the reference RISC-V simulators, supports
Core Local Interrupt (CLINT) controller @CLINT, and implements the relevant CSRs
as memory-mapped registers. Other simulators, like Venus @VenusRISCV, support
the Zicsr extension and include those registers, but don't support interrupts,
while simulators like @HaoziwanSim don't even support that extension.

// generic simulators
// #figure(
//   image("/img/asm-editor.specy.png", width: 75%),
//   caption: [Asm Editor @SpecySim],
// )
There are also simulators that support multiple ISAs, called _generic
simulators_, although there are many approaches. Asm Editor @SpecySim is a
multi-ISA simulator that uses other simulators as a base; specifically for
RISC-V, it uses RARS @RARSSim. It doesn't implement M-mode, only U-mode, and,
according to its manual, #quote[The implementation of user-mode exception
  handlers in RARS is not complete and does not fully conform to the RISC-V
  privilidged specification, but it is based upon that [...]]. The simulator
checks the `utvec`#footnote[The equivalent of `mtvec` for U-mode.] CSR is set,
and if not, the trap is handled by the simulator itself, either by printing an
error or performing some action in the case of OS calls (such as `ecall`).
Another approarch is to build a generic simulator that either allows the
definition of the ISA, as is the case of CREATOR @Camarmas2024CREATOR, or
simulates a generic processor that allows for the definition of the microcode,
such as WepSIM @wepsim2016a.


==== Interrupt simulation in CREATOR
CREATOR version 3.3 included some initial support for polled interrupts. It
allows putting special tags in registers in the ISA definition: an _interrupt
cause_ (`CAUSE`) register, which signals that an interrupt ocurred when its
value is different from `0x0`, and an _exception program counter_ (`EPC`), which
stores the address of the interrupted instruction (_program counter_, `PC`). As
shown in @alg:creator-execution-cycle, in CREATOR 5#footnote[As it will be
  mentioned in @chap:implementation, the process of implementing these new
  features in the simulator, among other factors, involved an almost complete
  rewrite of all its systems. The term "CREATOR 5" will be used to refer to the
  state of the project before these changes (version 5.0), and "CREATOR 6" will
  be used to refer to the state after the changes (version 6.0).]'s instruction
execution cycle, interrupts are checked before fetching the instruction,
therefore if an instruction generates an interrupt, the next instruction is the
one to get interrupted. These registers were only implemented in the MIPS-32
architecture provided in the simulator.


#algorithm(
  title: [CREATOR 5's instruction execution cycle],
  label: <alg:creator-execution-cycle>,
)[
  + *if* $#raw("CAUSE") != 0$ *then* #alg-comment[Interrupt detection]
    + $#raw("EPC") <- #raw("PC")$
    + $#raw("PC") <- 0$
    + $#raw("CAUSE") <- 0$
  - *end*
  + Fetch _instruction_
  + Decode _instruction_
  + Increment `PC`
  + Execute _instruction_
]



==== Interrupt simulation in WepSIM
WepSIM simulates what the authors call the "Elemental Processor"
(@fig:wepsim-ep), a simple 32-bit processor with a (micro)programmable control
unit (@fig:wepsim-cu). This allows the user to define not only what signals on
each instruction sets, but also how the instruction fetch is performed. For the
purpose of interrupt simulation, the control unit includes, connected to the
Control Bus, an interrupt request pin (`INT`) and an interrupt acknowledge pin
(`INTA`). The processor also includes a global interrupt enable _flag_ (`I`),
and an execution mode _flag_ (`U`), although they are currently unused in the
simulator.

#figure(
  image("/img/wepsim-ep-processor.svg", width: 80%),
  caption: [WepSIM's Elemental Processor @wepsim],
) <fig:wepsim-ep>

#figure(
  image("/img/wepsim-controlunit.svg", width: 75%),
  caption: [WepSIM's Control Unit @wepsim],
) <fig:wepsim-cu>

As mentioned, the user can customize how the Elemental Processor functions, but
WepSIM's handbook @wepsimHandbook[chap. 2.5.], as well as some provided
examples#footnote[Specifically, examples 9--13 in the "MIPS" example set.],
offer some guidance with regard to _how_ interrupts should be implemented.
WepSIM distinguishes between three types of interrupts: _exceptions_, errors
during the execution of an instruction; _system calls_, a special instruction
that executes a handler in privileged mode; and _interrupts_, caused by an I/O
device.

// INTV (ID) a RT1 a través de data bus
// microrutina con tabla de vectores
// en caso de dividir por cero, se deja en RT1, no es INT, es excepción, por lo que salta directamente a rutina

// ecall no genera interrupción, igual que dividir por cero

// microrutina guarda estado en stack (SR, PC)

#algorithm(
  title: [WepSIM's instruction execution cycle],
  label: <alg:wepsim-execution-cycle>,
)[
  + Fetch _instruction_ #line-label(<alg:wepsim-execution-cycle:fetch>)
  + Increment `PC`
  + *if* $#raw("INT") != 0$ *then* #alg-comment[Interrupt detection]
    + $#raw("INTA") <- 1$
    + $#raw("RT1") <- #raw("INTV")$
    - $#raw("INT") <- 0$ #alg-comment[Caused by I/O device]
    + $#raw("MEM[SP]") <- #raw("PC")$
    + Increment `SP`
    + $#raw("MEM[SP]") <- #raw("SR")$
    + Increment `SP`
    + $#raw("PC") <- #raw("MEM[RT1") times 4#raw("]")$
    + *goto* @alg:wepsim-execution-cycle:fetch
  - *end*
  + Decode _instruction_
  + Execute _instruction_
]


// sret retorna SR, PC
#algorithm(
  title: [WepSIM's return from interrupt instruction],
  label: <alg:wepsim-reti>,
)[
  + $#raw("SR") <- #raw("MEM[SP]")$
  + Increment `SP`
  + $#raw("PC") <- #raw("MEM[SP]")$
  + Increment `SP`
]


// no se deshabilita I (pero se debería)


// ktext, kdata




== Timers


== Memory-mapped I/O
