classDiagram
    direction TB

    class Device {
        <<abstract>>
        + readonly ctrl_addr: number
        + readonly status_addr: number
        + readonly data: number
        + enabled: boolean
        + memory: Memory
        + constructor(addresses, enabled=true)
        + isDeviceAddr(addr) boolean
        + reset()
        + clear()
        + handler()
    }

    class Console Device {
        + handler()
        %% - write(value, type)
        %% - prepareRead(type)
    }

    class OS Driver {
        + handler()
    }

    class Device Manager {
        + devices: Map~string, Device~
        + constructor(devices)
        + checkDeviceAddr(addr) string
        + wakeDevice(id)
        + handleDevices()
        + resetDevices()
    }

    %% relationships
    Device <|-- ConsoleDevice
    Device <|-- OSDriver
    DeviceManager  o-- Device: uses
