classDiagram
    class Timer Manager {
        + constructor(actions)
        + timerAdvance()
        + timerHandler()
        + timerIsEnabled()
        + handle(currentCycles: number)
    }

    %% class Architecture {
    %%     <<interface>>
    %%     + TimerConfig timer
    %% }

    %% class TimerConfig {
    %%     <<interface>>
    %%     + string advance
    %%     + string handler
    %%     + string is_enabled
    %%     + number tick_cycles
    %% }

    %% TimerManager --> Architecture : depends on
    %% Architecture *-- TimerConfig : contains